import { portalApolloClient } from './portalApollo';
import { PORTAL_LOGIN_QUERY } from './portalQueries';
import { MemberUser } from '../types';
import { hashPin } from '../utils/hashPin';

const PORTAL_SESSION_KEY = 'hkm_portal_session';
const SESSION_TIMEOUT_MS = 60 * 60 * 1000; // 1 hour

export const portalAuthService = {
  /**
   * LOGIN — Validates Member ID + PIN against the Supabase `members` table.
   * The PIN is auto-generated by the CMS admin app when a Registration Fee
   * is recorded. `is_portal_active` is set to true at that same moment.
   */
  async loginWithMembership(membershipNumber: string, pin: string) {
    const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://tkzxzriivbbzdvjgrdhk.supabase.co';
    const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || '';

    const response = await fetch(`${supabaseUrl}/functions/v1/portal-login`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${supabaseAnonKey}`,
      },
      body: JSON.stringify({ membershipNumber, pin }),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(
        errorData.error ||
          'Invalid Membership Number or PIN. If you have not paid your Registration Fee, please contact the church office.',
      );
    }

    const { token, member } = await response.json();

    // Save session to localStorage
    const session: MemberUser = {
      ...member,
      token, // Save the token to pass to Apollo client later
      expiresAt: Date.now() + SESSION_TIMEOUT_MS,
    };

    localStorage.setItem(PORTAL_SESSION_KEY, JSON.stringify(session));

    return session;
  },

  /**
   * LOGOUT — Clears the portal session from localStorage.
   */
  logout() {
    localStorage.removeItem(PORTAL_SESSION_KEY);
  },

  /**
   * IS AUTHENTICATED — checks whether a portal session exists and is valid.
   * Also implements rolling sessions by extending expiration on activity.
   */
  isAuthenticated(): boolean {
    const sessionStr = localStorage.getItem(PORTAL_SESSION_KEY);
    if (!sessionStr) return false;

    try {
      const session = JSON.parse(sessionStr) as MemberUser;
      if (session.expiresAt && Date.now() > session.expiresAt) {
        this.logout();
        return false;
      }

      // Extend session (rolling 1 hour)
      session.expiresAt = Date.now() + SESSION_TIMEOUT_MS;
      localStorage.setItem(PORTAL_SESSION_KEY, JSON.stringify(session));
      return true;
    } catch {
      this.logout();
      return false;
    }
  },

  /**
   * GET CURRENT USER — Returns the logged-in member from the local session.
   */
  getCurrentUser(): MemberUser | null {
    if (!this.isAuthenticated()) return null;

    const sessionStr = localStorage.getItem(PORTAL_SESSION_KEY);
    if (!sessionStr) return null;

    try {
      return JSON.parse(sessionStr) as MemberUser;
    } catch {
      return null;
    }
  },

  /**
   * REQUEST PIN — Instructs the member to contact the church office.
   */
  async requestPin(_membershipNumber: string) {
    throw new Error(
      'To request a new PIN, please contact the church office. Your PIN is automatically sent when you pay your Registration Fee.',
    );
  },
};
